// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGeminiStatus() {
  return window['go']['main']['App']['GetGeminiStatus']();
}

export function JoinMeeting(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['JoinMeeting'](arg1, arg2, arg3, arg4, arg5);
}

export function LeaveCall() {
  return window['go']['main']['App']['LeaveCall']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
