// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetGeminiStatus():Promise<main.GeminiStatus>;

export function JoinMeeting(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function LeaveCall():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;
